[sqlserver]
server   = SERVIDOR-PPAL,1433
database = SIGAP
driver   = ODBC Driver 17 for SQL Server
user     = MP
password = Munipa*Pocito

[output]
dir = "D:/sube expedientes"

[nube]
ssh_host          = 137.131.197.13
ssh_port          = 22
ssh_user          = ubuntu
llave             = D:/subida/pocito-server-openssh.key
db_user           = admin_sql
db_pass           = MpSj*30673
db_name           = sigap_expedientes
dir_remoto        = /tmp/
dias_movimientos  = 1855

[watchdog]
; Intervalo de chequeo en segundos (300 = 5 minutos)
intervalo_segundos = 300
